version: '3.8'

services:
  docs:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped
    
  docs-dev:
    build:
      context: .
      target: build
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start --host 0.0.0.0
    restart: unless-stopped
    profiles:
      - dev 